#!/bin/sh
# Un comment and use set +e to ignore and set -e to enable 'exit on error control'
set +e
# Un comment the line below to help debug scripts by printing a trace of the script commands
#set -x
# PX4FMU startup script.
#
# NOTE: environment variable references:
#    If the dollar sign ('$') is followed by a left bracket ('{') then the
#    variable name is terminated with the right bracket character ('}').
#    Otherwise, the variable name goes to the end of the argument.
#
#
# NOTE: COMMENT LINES ARE REMOVED BEFORE STORED IN ROMFS.
#
#------------------------------------------------------------------------------

#
# Set default paramter values.
# Do not add intra word spaces
# it wastes flash
#

set SDCARD_DEVPATH /dev/mmcsd0

#
# Print full system version.
#
ver all

if [ -d "/dev/rptun" ]
then
	echo "Starting RPTUN"
	rptun start /dev/rptun/mpfs-ihc
	set REMOTE_IPADDR "192.168.201.240"
else
	set REMOTE_IPADDR "192.168.200.100"
fi

#
# Try to mount the microSD card.
#
if [ -b $SDCARD_DEVPATH ]
then
	if mount -t vfat $SDCARD_DEVPATH /fs/microsd
	then
		if [ -f "/fs/microsd/.format" ]
		then
			echo "INFO [init] format ${SDCARD_DEVPATH} requested (/fs/microsd/.format)"
			set SDCARD_FORMAT yes
			rm /fs/microsd/.format
			umount /fs/microsd

		else
			set SDCARD_AVAILABLE yes
		fi
	fi
fi

moi_agent start

if moi_agent cmp M
then
	echo "M-O-I state: Maintenance"
	. /etc/init.d/rc.m_state
fi

if moi_agent cmp O
then
	echo "M-O-I state: Operational"
	. /etc/init.d/rc.o_state
fi

if moi_agent cmp I
then
	echo "M-O-I state: Init"
	. /etc/init.d/rc.i_state
fi

unset SDCARD_DEVPATH
