#!/bin/sh
# Un comment and use set +e to ignore and set -e to enable 'exit on error control'
set +e
# Un comment the line below to help debug scripts by printing a trace of the script commands
#set -x
# PX4FMU startup script.
#
# NOTE: environment variable references:
#    If the dollar sign ('$') is followed by a left bracket ('{') then the
#    variable name is terminated with the right bracket character ('}').
#    Otherwise, the variable name goes to the end of the argument.
#
#
# NOTE: COMMENT LINES ARE REMOVED BEFORE STORED IN ROMFS.
#
#------------------------------------------------------------------------------

#
# Set default paramter values.
# Do not add intra word spaces
# it wastes flash
#
set R /
set RC_M_STATE ${R}etc/init.d/rc.m_state
set RC_O_STATE ${R}etc/init.d/rc.o_state
set RC_I_STATE ${R}etc/init.d/rc.i_state
set MOI_STATE I

#
# Optional board path defaults: rc.board_paths
#
set BOARD_RC_PATHS ${R}etc/init.d/rc.board_paths
if [ -f $BOARD_RC_PATHS ]
then
	echo "Board path defaults: ${BOARD_RC_PATHS}"
	. $BOARD_RC_PATHS
fi
unset BOARD_RC_PATHS


#
# Print full system version.
#

if moi_agent cmp M
then
	set MOI_STATE M
        . ${RC_M_STATE}
        echo "M-O-I state: Maintenance"
else
if moi_agent cmp O
then
	set MOI_STATE O
        . ${RC_O_STATE}
        echo "M-O-I state: Operational"
else
if moi_agent cmp I
then
	set MOI_STATE I
        . ${RC_I_STATE}
        echo "M-O-I state: Init"
fi
fi
fi


unset R
unset RC_M_STATE
unset RC_O_STATE
unset RC_I_STATE
