#!/bin/sh
#
# @name SSRC ARWing
#
# @type Flying Wing
# @class Plane
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. /etc/init.d/rc.fw_defaults

# non-default parameters from field test with UAE (17.8.2023) https://px4-flight-review.ssrc.fi/plot_app?log=ef88674c-519f-4528-88f3-6bd6cb64b449

# Airspeed parameters
param set-default ASPD_DO_CHECKS 23
param set-default ASPD_SCALE_1 1.0329
param set-default FW_AIRSPD_MAX 22.0
param set-default FW_AIRSPD_MIN 13.0
param set-default FW_AIRSPD_STALL 12.0
param set-default FW_AIRSPD_TRIM 18.0

# Battery parameters
param set-default BAT1_N_CELLS 4
param set-default BAT1_R_INTERNAL 0.0050
param set-default BAT1_SOURCE 0
param set-default BAT1_V_CHARGED 4.0500
param set-default BAT1_V_EMPTY 3.6000
param set-default BAT1_V_LOAD_DROP 0.1000

param set-default BAT2_N_CELLS 0
param set-default BAT2_R_INTERNAL 0.0050
param set-default BAT2_SOURCE -1
param set-default BAT2_V_CHARGED 4.0500
param set-default BAT2_V_EMPTY 3.6000
param set-default BAT2_V_LOAD_DROP 0.1000

# Disable internal magnetometer
param set CAL_MAG0_PRIO 0

# Control allocator parameters
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.1500
param set-default CA_SV_CS0_TRIM 0.0
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_Y 0.0
param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS1_TRIM 0.0
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TRQ_Y 0.0
param set-default CA_SV_CS1_TYPE 6
param set-default CA_SV_CS_COUNT 2

# Circuit breaker for IO safety
param set-default CBRK_IO_SAFETY 0

# COM
param set-default COM_ARM_ARSP_EN 1
param set-default COM_DISARM_PRFLT -1.0
param set-default COM_FLIGHT_UUID 32
param set-default COM_FLTMODE1 6
param set-default COM_FLTMODE4 2
param set-default COM_FLTMODE6 5
param set-default COM_POS_FS_DELAY 5
param set-default COM_POS_FS_EPH 15.0
param set-default COM_POS_FS_EPV 30.0
param set-default COM_PREARM_MODE 1
param set-default COM_VEL_FS_EVH 5.0

# EKF2
param set-default EKF2_ARSP_THR 8.0
param set-default EKF2_EVA_NOISE 0.0500
param set-default EKF2_FUSE_BETA 1
param set-default EKF2_GPS_CHECK 21
param set-default EKF2_MAG_ACCLIM 0.0
param set-default EKF2_MAG_DECL 9.8430
param set-default EKF2_MAG_YAWLIM 0.0
param set-default EKF2_MULTI_IMU 3
param set-default EKF2_REQ_EPH 10.0
param set-default EKF2_REQ_EPV 10.0
param set-default EKF2_REQ_HDRIFT 0.5
param set-default EKF2_REQ_SACC 1.0
param set-default EKF2_REQ_VDRIFT 1.0

# Fixed wing specific
param set-default FW_DTRIM_P_FLPS 0.0
param set-default FW_DTRIM_P_SPOIL 0.0
param set-default FW_DTRIM_R_FLPS 0.0
param set-default FW_L1_DAMPING 0.75
param set-default FW_L1_PERIOD 20.0
param set-default FW_L1_R_SLEW_MAX 90.0
param set-default FW_LAUN_DETCN_ON 1
param set-default FW_MAN_R_MAX 60.0
param set-default FW_RR_IMAX 0.4000
param set-default FW_T_I_GAIN_THR 0.3000
param set-default FW_T_SPD_OMEGA 2.0
param set-default FW_T_TAS_R_TC 0.2000
param set-default FW_USE_NPFG 1
param set-default FW_YR_IMAX 0.4000

# [EXPERIMENTAL] Use Pre-emptive geofence triggering
param set-default GF_PREDICT 1

# GPS
param set-default GPS_1_CONFIG 201
param set-default GPS_2_CONFIG 0
param set-default GPS_UBX_DYNMODEL 8

# Mavlink parameters
param set-default MAV_0_CONFIG 101
param set-default MAV_0_FLOW_CTRL 2
param set-default MAV_0_FORWARD 1
param set-default MAV_0_MODE 0
param set-default MAV_0_RADIO_CTL 1
param set-default MAV_0_RATE 1200
param set-default MAV_1_CONFIG 0
param set-default MAV_2_CONFIG 0
param set-default MAV_ODOM_LP 0
param set-default MAV_TYPE 1

# Mission parameters
param set-default MIS_DIST_WPS 5000.0
param set-default MIS_TAKEOFF_ALT 25.0
param set-default MIS_TKO_LAND_REQ 2

# Navigation
param set-default NAV_TRAFF_A_RADM 500.0
param set-default NAV_TRAFF_A_RADU 10.0

# PWM
param set-default PWM_AUX_DIS1 900
param set-default PWM_AUX_DIS10 900
param set-default PWM_AUX_DIS2 900
param set-default PWM_AUX_DIS3 900
param set-default PWM_AUX_DIS4 900
param set-default PWM_AUX_DIS5 900
param set-default PWM_AUX_DIS6 900
param set-default PWM_AUX_DIS7 900
param set-default PWM_AUX_DIS8 900
param set-default PWM_AUX_DIS9 900
param set-default PWM_AUX_MAX1 2000
param set-default PWM_AUX_MAX10 2000
param set-default PWM_AUX_MAX2 2000
param set-default PWM_AUX_MAX3 2000
param set-default PWM_AUX_MAX4 2000
param set-default PWM_AUX_MAX5 2000
param set-default PWM_AUX_MAX6 2000
param set-default PWM_AUX_MAX7 2000
param set-default PWM_AUX_MAX8 2000
param set-default PWM_AUX_MAX9 2000
param set-default PWM_AUX_MIN1 1000
param set-default PWM_AUX_MIN10 1000
param set-default PWM_AUX_MIN2 1000
param set-default PWM_AUX_MIN3 1000
param set-default PWM_AUX_MIN4 1000
param set-default PWM_AUX_MIN5 1000
param set-default PWM_AUX_MIN6 1000
param set-default PWM_AUX_MIN7 1000
param set-default PWM_AUX_MIN8 1000
param set-default PWM_AUX_MIN9 1000
param set-default PWM_AUX_REV 0
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_DIS3 900
param set-default PWM_MAIN_DIS4 900
param set-default PWM_MAIN_DIS5 900
param set-default PWM_MAIN_DIS6 900
param set-default PWM_MAIN_DIS7 900
param set-default PWM_MAIN_DIS8 900
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC4 101
param set-default PWM_MAIN_MAX1 2000
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_MAIN_MAX3 2000
param set-default PWM_MAIN_MAX4 2000
param set-default PWM_MAIN_MAX5 2000
param set-default PWM_MAIN_MAX6 2000
param set-default PWM_MAIN_MAX7 2000
param set-default PWM_MAIN_MAX8 2000
param set-default PWM_MAIN_MIN1 1000
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 1000
param set-default PWM_MAIN_MIN5 1000
param set-default PWM_MAIN_MIN6 1000
param set-default PWM_MAIN_MIN7 1000
param set-default PWM_MAIN_MIN8 1000
param set-default PWM_MAIN_REV 2
param set-default PWM_MAIN_TIM0 50
param set-default PWM_MAIN_TIM1 400
param set-default PWM_MAIN_TIM2 400

# Misc
param set-default RTL_LAND_DELAY -1.0
param set-default RTL_RETURN_ALT 30.0
param set-default RTL_TYPE 1
param set-default RWTO_L1_PERIOD 5.0
param set-default SDLOG_EXCH_KEY 2
param set-default SDLOG_KEY 3
param set-default SENS_EN_INA226 1
param set-default SENS_EXT_I2C_PRB 0
param set-default SENS_IMU_MODE 0
param set-default SER_TEL1_BAUD 57600
param set-default SYS_AUTOSTART 3000
param set-default SYS_DM_BACKEND 1
param set-default SYS_USE_IO 1
param set-default VT_B_REV_DEL 0.0

# XRCE
param set-default XRCE_DDS_0_CFG 0
param set-default XRCE_DDS_DOM_ID 0
param set-default XRCE_DDS_KEY 1
