# Generate apps.rs and Cargo.toml for rust_bridge based on which Rust modules are in the build

get_property(RUST_MODULES GLOBAL PROPERTY PX4_RUST_MODULES)

if(NOT RUST_MODULES)
	# On first configure, modules haven't been registered yet - use empty list
	# The files will be regenerated on the next configure with the actual modules
	set(RUST_MODULES "")
endif()

# Generate the apps.rs file content
set(APPS_RS_CONTENT "// Auto-generated file - DO NOT EDIT\n")
set(APPS_RS_CONTENT "${APPS_RS_CONTENT}// Generated by cmake/generate_rust_apps.cmake\n\n")
set(APPS_RS_CONTENT "${APPS_RS_CONTENT}pub fn get_flat_mode_apps() -> Vec<(&'static str, fn(u32, *mut *mut u8) -> i32)> {\n")
set(APPS_RS_CONTENT "${APPS_RS_CONTENT}    vec![\n")

# Generate Cargo.toml dependencies
set(CARGO_DEPS "")

# Add each Rust module
foreach(rust_mod ${RUST_MODULES})
	set(APPS_RS_CONTENT "${APPS_RS_CONTENT}        (\"${rust_mod}\", ${rust_mod}::entrypoint),\n")
	set(CARGO_DEPS "${CARGO_DEPS}${rust_mod} = { path = \"../../../modules/${rust_mod}/${rust_mod}\" }\n")
endforeach()

set(APPS_RS_CONTENT "${APPS_RS_CONTENT}    ]\n}\n")

# Write the apps.rs file
file(WRITE "${APPS_RS_FILE}" "${APPS_RS_CONTENT}")

# Generate Cargo.toml content
set(CARGO_CONTENT "# Auto-generated file - DO NOT EDIT\n")
set(CARGO_CONTENT "${CARGO_CONTENT}# Generated by cmake/generate_rust_apps.cmake\n\n")
set(CARGO_CONTENT "${CARGO_CONTENT}[package]\n")
set(CARGO_CONTENT "${CARGO_CONTENT}name = \"rust_bridge\"\n")
set(CARGO_CONTENT "${CARGO_CONTENT}version = \"0.1.0\"\n")
set(CARGO_CONTENT "${CARGO_CONTENT}edition = \"2021\"\n\n")
set(CARGO_CONTENT "${CARGO_CONTENT}[lib]\n")
set(CARGO_CONTENT "${CARGO_CONTENT}crate-type = [\"staticlib\"]\n\n")
set(CARGO_CONTENT "${CARGO_CONTENT}[profile.dev]\n")
set(CARGO_CONTENT "${CARGO_CONTENT}panic = \"abort\"\n\n")
set(CARGO_CONTENT "${CARGO_CONTENT}[profile.release]\n")
set(CARGO_CONTENT "${CARGO_CONTENT}panic = \"abort\"\n\n")
set(CARGO_CONTENT "${CARGO_CONTENT}[dependencies]\n")
set(CARGO_CONTENT "${CARGO_CONTENT}px4_nuttx = { path = \"../px4_nuttx_lib\" }\n")
set(CARGO_CONTENT "${CARGO_CONTENT}px4_nuttx_macros = { path = \"../px4_nuttx_macros\" }\n")
set(CARGO_CONTENT "${CARGO_CONTENT}${CARGO_DEPS}")

# Write the Cargo.toml file
file(WRITE "${CARGO_TOML_FILE}" "${CARGO_CONTENT}")
