on:
  workflow_call:
    inputs:
      product:
        required: true
        type: string
      clone_public:
        required: false
        type: boolean
        default: false
      crypto_driver:
        required: false
        type: boolean
        default: false
    secrets:
      GH_REPO_TOKEN:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout px4-firmware
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          # if we clone_public, then do not clone submodules, otherwise 'recursive'
          submodules: ${{ inputs.clone_public == true && 'false' || 'recursive' }}
          path: px4-firmware
          fetch-depth: 0
      - name: Checkout PF Athena crypto driver
        if: ${{ inputs.crypto_driver }}
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          repository: tiiuae/pf_crypto
          path: px4-firmware/platforms/nuttx/NuttX/nuttx/arch/risc-v/src/mpfs/crypto
      - name: Run px4-firmware ${{ inputs.product }} build
        run: |
          set -eux
          mkdir -p bin
          cd px4-firmware/
          # run clone_public.sh if clone_public flag is provided
          if [[ ${{ inputs.clone_public }} = true ]]; then ./clone_public.sh; fi
          ./build.sh ../bin/ ${{ inputs.product }}
          ls ../bin
      - name: Upload ${{ inputs.product }}
        uses: actions/upload-artifact@v3
        with:
          name: pixhawk
          path: bin/
          retention-days: 1
