name: Build Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build-saluki-v1:
        description: 'Build Saluki-v1 product manually'
        required: true
        default: saluki-v1_default,saluki-v1_bootloader,saluki-v1_amp,saluki-v1_protected

permissions:
  contents: read
  packages: write

jobs:
  fc_matrix:
    strategy:
      fail-fast: false
      matrix:
        product: [pixhawk, saluki-v2_default, saluki-v2_bootloader, saluki-v2_amp, saluki-v2_protected, saluki-pi_default, saluki-pi_bootloader, saluki-pi_amp, saluki-pi_protected, saluki-v1_default, saluki-v1_bootloader, saluki-v1_amp, saluki-v1_protected]

    if: |
     matrix.product != 'saluki-v1_default' && github.event.inputs.version != 'saluki-v1_default'
     matrix.product != 'saluki-v1_bootloader' && github.event.inputs.version != 'saluki-v1_bootloader'
     matrix.product != 'saluki-v1_amp' && github.event.inputs.version != 'saluki-v1_amp'
     matrix.product != 'saluki-v1_protected' && github.event.inputs.version != 'saluki-v1_protected'

    uses: ./.github/workflows/tiiuae-pixhawk-and-saluki-builder.yaml
    with:
      product: ${{ matrix.product }}
      enabled: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.build-saluki-v1, matrix.product)) }}
    secrets: inherit

